/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vy.payroll.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.vy.payroll.model.CtcDetail;
import com.vy.payroll.model.CtcDetailModel;
import com.vy.payroll.model.CtcDetailSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CtcDetail service. Represents a row in the &quot;ctc_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CtcDetailModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CtcDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CtcDetailImpl
 * @see CtcDetail
 * @see CtcDetailModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CtcDetailModelImpl extends BaseModelImpl<CtcDetail>
	implements CtcDetailModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ctc detail model instance should use the {@link CtcDetail} interface instead.
	 */
	public static final String TABLE_NAME = "ctc_details";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ctc", Types.INTEGER },
			{ "hra", Types.INTEGER },
			{ "ma", Types.INTEGER },
			{ "ca", Types.INTEGER },
			{ "ta", Types.INTEGER },
			{ "pf", Types.INTEGER },
			{ "sa", Types.INTEGER },
			{ "incomeTax", Types.INTEGER },
			{ "proffesionalTax", Types.INTEGER },
			{ "basicSalary", Types.INTEGER },
			{ "contributionAmt", Types.INTEGER },
			{ "gratuity", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ctc", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("hra", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ma", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ca", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ta", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("pf", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sa", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("incomeTax", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("proffesionalTax", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("basicSalary", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("contributionAmt", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("gratuity", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table ctc_details (ctc INTEGER not null primary key,hra INTEGER,ma INTEGER,ca INTEGER,ta INTEGER,pf INTEGER,sa INTEGER,incomeTax INTEGER,proffesionalTax INTEGER,basicSalary INTEGER,contributionAmt INTEGER,gratuity INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table ctc_details";
	public static final String ORDER_BY_JPQL = " ORDER BY ctcDetail.ctc ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ctc_details.ctc ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.vy.payroll.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vy.payroll.model.CtcDetail"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.vy.payroll.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vy.payroll.model.CtcDetail"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CtcDetail toModel(CtcDetailSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CtcDetail model = new CtcDetailImpl();

		model.setCtc(soapModel.getCtc());
		model.setHra(soapModel.getHra());
		model.setMa(soapModel.getMa());
		model.setCa(soapModel.getCa());
		model.setTa(soapModel.getTa());
		model.setPf(soapModel.getPf());
		model.setSa(soapModel.getSa());
		model.setIncomeTax(soapModel.getIncomeTax());
		model.setProffesionalTax(soapModel.getProffesionalTax());
		model.setBasicSalary(soapModel.getBasicSalary());
		model.setContributionAmt(soapModel.getContributionAmt());
		model.setGratuity(soapModel.getGratuity());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CtcDetail> toModels(CtcDetailSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CtcDetail> models = new ArrayList<CtcDetail>(soapModels.length);

		for (CtcDetailSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.vy.payroll.service.util.ServiceProps.get(
				"lock.expiration.time.com.vy.payroll.model.CtcDetail"));

	public CtcDetailModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _ctc;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setCtc(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ctc;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CtcDetail.class;
	}

	@Override
	public String getModelClassName() {
		return CtcDetail.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ctc", getCtc());
		attributes.put("hra", getHra());
		attributes.put("ma", getMa());
		attributes.put("ca", getCa());
		attributes.put("ta", getTa());
		attributes.put("pf", getPf());
		attributes.put("sa", getSa());
		attributes.put("incomeTax", getIncomeTax());
		attributes.put("proffesionalTax", getProffesionalTax());
		attributes.put("basicSalary", getBasicSalary());
		attributes.put("contributionAmt", getContributionAmt());
		attributes.put("gratuity", getGratuity());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer ctc = (Integer)attributes.get("ctc");

		if (ctc != null) {
			setCtc(ctc);
		}

		Integer hra = (Integer)attributes.get("hra");

		if (hra != null) {
			setHra(hra);
		}

		Integer ma = (Integer)attributes.get("ma");

		if (ma != null) {
			setMa(ma);
		}

		Integer ca = (Integer)attributes.get("ca");

		if (ca != null) {
			setCa(ca);
		}

		Integer ta = (Integer)attributes.get("ta");

		if (ta != null) {
			setTa(ta);
		}

		Integer pf = (Integer)attributes.get("pf");

		if (pf != null) {
			setPf(pf);
		}

		Integer sa = (Integer)attributes.get("sa");

		if (sa != null) {
			setSa(sa);
		}

		Integer incomeTax = (Integer)attributes.get("incomeTax");

		if (incomeTax != null) {
			setIncomeTax(incomeTax);
		}

		Integer proffesionalTax = (Integer)attributes.get("proffesionalTax");

		if (proffesionalTax != null) {
			setProffesionalTax(proffesionalTax);
		}

		Integer basicSalary = (Integer)attributes.get("basicSalary");

		if (basicSalary != null) {
			setBasicSalary(basicSalary);
		}

		Integer contributionAmt = (Integer)attributes.get("contributionAmt");

		if (contributionAmt != null) {
			setContributionAmt(contributionAmt);
		}

		Integer gratuity = (Integer)attributes.get("gratuity");

		if (gratuity != null) {
			setGratuity(gratuity);
		}
	}

	@JSON
	@Override
	public int getCtc() {
		return _ctc;
	}

	@Override
	public void setCtc(int ctc) {
		_ctc = ctc;
	}

	@JSON
	@Override
	public int getHra() {
		return _hra;
	}

	@Override
	public void setHra(int hra) {
		_hra = hra;
	}

	@JSON
	@Override
	public int getMa() {
		return _ma;
	}

	@Override
	public void setMa(int ma) {
		_ma = ma;
	}

	@JSON
	@Override
	public int getCa() {
		return _ca;
	}

	@Override
	public void setCa(int ca) {
		_ca = ca;
	}

	@JSON
	@Override
	public int getTa() {
		return _ta;
	}

	@Override
	public void setTa(int ta) {
		_ta = ta;
	}

	@JSON
	@Override
	public int getPf() {
		return _pf;
	}

	@Override
	public void setPf(int pf) {
		_pf = pf;
	}

	@JSON
	@Override
	public int getSa() {
		return _sa;
	}

	@Override
	public void setSa(int sa) {
		_sa = sa;
	}

	@JSON
	@Override
	public int getIncomeTax() {
		return _incomeTax;
	}

	@Override
	public void setIncomeTax(int incomeTax) {
		_incomeTax = incomeTax;
	}

	@JSON
	@Override
	public int getProffesionalTax() {
		return _proffesionalTax;
	}

	@Override
	public void setProffesionalTax(int proffesionalTax) {
		_proffesionalTax = proffesionalTax;
	}

	@JSON
	@Override
	public int getBasicSalary() {
		return _basicSalary;
	}

	@Override
	public void setBasicSalary(int basicSalary) {
		_basicSalary = basicSalary;
	}

	@JSON
	@Override
	public int getContributionAmt() {
		return _contributionAmt;
	}

	@Override
	public void setContributionAmt(int contributionAmt) {
		_contributionAmt = contributionAmt;
	}

	@JSON
	@Override
	public int getGratuity() {
		return _gratuity;
	}

	@Override
	public void setGratuity(int gratuity) {
		_gratuity = gratuity;
	}

	@Override
	public CtcDetail toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CtcDetail)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CtcDetailImpl ctcDetailImpl = new CtcDetailImpl();

		ctcDetailImpl.setCtc(getCtc());
		ctcDetailImpl.setHra(getHra());
		ctcDetailImpl.setMa(getMa());
		ctcDetailImpl.setCa(getCa());
		ctcDetailImpl.setTa(getTa());
		ctcDetailImpl.setPf(getPf());
		ctcDetailImpl.setSa(getSa());
		ctcDetailImpl.setIncomeTax(getIncomeTax());
		ctcDetailImpl.setProffesionalTax(getProffesionalTax());
		ctcDetailImpl.setBasicSalary(getBasicSalary());
		ctcDetailImpl.setContributionAmt(getContributionAmt());
		ctcDetailImpl.setGratuity(getGratuity());

		ctcDetailImpl.resetOriginalValues();

		return ctcDetailImpl;
	}

	@Override
	public int compareTo(CtcDetail ctcDetail) {
		int primaryKey = ctcDetail.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CtcDetail)) {
			return false;
		}

		CtcDetail ctcDetail = (CtcDetail)obj;

		int primaryKey = ctcDetail.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CtcDetail> toCacheModel() {
		CtcDetailCacheModel ctcDetailCacheModel = new CtcDetailCacheModel();

		ctcDetailCacheModel.ctc = getCtc();

		ctcDetailCacheModel.hra = getHra();

		ctcDetailCacheModel.ma = getMa();

		ctcDetailCacheModel.ca = getCa();

		ctcDetailCacheModel.ta = getTa();

		ctcDetailCacheModel.pf = getPf();

		ctcDetailCacheModel.sa = getSa();

		ctcDetailCacheModel.incomeTax = getIncomeTax();

		ctcDetailCacheModel.proffesionalTax = getProffesionalTax();

		ctcDetailCacheModel.basicSalary = getBasicSalary();

		ctcDetailCacheModel.contributionAmt = getContributionAmt();

		ctcDetailCacheModel.gratuity = getGratuity();

		return ctcDetailCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{ctc=");
		sb.append(getCtc());
		sb.append(", hra=");
		sb.append(getHra());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ca=");
		sb.append(getCa());
		sb.append(", ta=");
		sb.append(getTa());
		sb.append(", pf=");
		sb.append(getPf());
		sb.append(", sa=");
		sb.append(getSa());
		sb.append(", incomeTax=");
		sb.append(getIncomeTax());
		sb.append(", proffesionalTax=");
		sb.append(getProffesionalTax());
		sb.append(", basicSalary=");
		sb.append(getBasicSalary());
		sb.append(", contributionAmt=");
		sb.append(getContributionAmt());
		sb.append(", gratuity=");
		sb.append(getGratuity());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.vy.payroll.model.CtcDetail");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ctc</column-name><column-value><![CDATA[");
		sb.append(getCtc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hra</column-name><column-value><![CDATA[");
		sb.append(getHra());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ca</column-name><column-value><![CDATA[");
		sb.append(getCa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ta</column-name><column-value><![CDATA[");
		sb.append(getTa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pf</column-name><column-value><![CDATA[");
		sb.append(getPf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sa</column-name><column-value><![CDATA[");
		sb.append(getSa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>incomeTax</column-name><column-value><![CDATA[");
		sb.append(getIncomeTax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>proffesionalTax</column-name><column-value><![CDATA[");
		sb.append(getProffesionalTax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>basicSalary</column-name><column-value><![CDATA[");
		sb.append(getBasicSalary());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contributionAmt</column-name><column-value><![CDATA[");
		sb.append(getContributionAmt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gratuity</column-name><column-value><![CDATA[");
		sb.append(getGratuity());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CtcDetail.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CtcDetail.class, ModelWrapper.class
		};
	private int _ctc;
	private int _hra;
	private int _ma;
	private int _ca;
	private int _ta;
	private int _pf;
	private int _sa;
	private int _incomeTax;
	private int _proffesionalTax;
	private int _basicSalary;
	private int _contributionAmt;
	private int _gratuity;
	private CtcDetail _escapedModel;
}