/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vy.payroll.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.vy.payroll.model.LeaveRequest;
import com.vy.payroll.service.LeaveRequestService;
import com.vy.payroll.service.persistence.Admin_detailsPersistence;
import com.vy.payroll.service.persistence.AdvanceSalaryRecordFinder;
import com.vy.payroll.service.persistence.AdvanceSalaryRecordPersistence;
import com.vy.payroll.service.persistence.CtcDetailPersistence;
import com.vy.payroll.service.persistence.DepartmentPersistence;
import com.vy.payroll.service.persistence.DocumentFinder;
import com.vy.payroll.service.persistence.DocumentPersistence;
import com.vy.payroll.service.persistence.EmployeeDetailsPersistence;
import com.vy.payroll.service.persistence.LeaveRequestFinder;
import com.vy.payroll.service.persistence.LeaveRequestPersistence;
import com.vy.payroll.service.persistence.PayslipDetailsPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the leave request remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.vy.payroll.service.impl.LeaveRequestServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.vy.payroll.service.impl.LeaveRequestServiceImpl
 * @see com.vy.payroll.service.LeaveRequestServiceUtil
 * @generated
 */
public abstract class LeaveRequestServiceBaseImpl extends BaseServiceImpl
	implements LeaveRequestService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.vy.payroll.service.LeaveRequestServiceUtil} to access the leave request remote service.
	 */

	/**
	 * Returns the admin_details local service.
	 *
	 * @return the admin_details local service
	 */
	public com.vy.payroll.service.Admin_detailsLocalService getAdmin_detailsLocalService() {
		return admin_detailsLocalService;
	}

	/**
	 * Sets the admin_details local service.
	 *
	 * @param admin_detailsLocalService the admin_details local service
	 */
	public void setAdmin_detailsLocalService(
		com.vy.payroll.service.Admin_detailsLocalService admin_detailsLocalService) {
		this.admin_detailsLocalService = admin_detailsLocalService;
	}

	/**
	 * Returns the admin_details remote service.
	 *
	 * @return the admin_details remote service
	 */
	public com.vy.payroll.service.Admin_detailsService getAdmin_detailsService() {
		return admin_detailsService;
	}

	/**
	 * Sets the admin_details remote service.
	 *
	 * @param admin_detailsService the admin_details remote service
	 */
	public void setAdmin_detailsService(
		com.vy.payroll.service.Admin_detailsService admin_detailsService) {
		this.admin_detailsService = admin_detailsService;
	}

	/**
	 * Returns the admin_details persistence.
	 *
	 * @return the admin_details persistence
	 */
	public Admin_detailsPersistence getAdmin_detailsPersistence() {
		return admin_detailsPersistence;
	}

	/**
	 * Sets the admin_details persistence.
	 *
	 * @param admin_detailsPersistence the admin_details persistence
	 */
	public void setAdmin_detailsPersistence(
		Admin_detailsPersistence admin_detailsPersistence) {
		this.admin_detailsPersistence = admin_detailsPersistence;
	}

	/**
	 * Returns the advance salary record local service.
	 *
	 * @return the advance salary record local service
	 */
	public com.vy.payroll.service.AdvanceSalaryRecordLocalService getAdvanceSalaryRecordLocalService() {
		return advanceSalaryRecordLocalService;
	}

	/**
	 * Sets the advance salary record local service.
	 *
	 * @param advanceSalaryRecordLocalService the advance salary record local service
	 */
	public void setAdvanceSalaryRecordLocalService(
		com.vy.payroll.service.AdvanceSalaryRecordLocalService advanceSalaryRecordLocalService) {
		this.advanceSalaryRecordLocalService = advanceSalaryRecordLocalService;
	}

	/**
	 * Returns the advance salary record remote service.
	 *
	 * @return the advance salary record remote service
	 */
	public com.vy.payroll.service.AdvanceSalaryRecordService getAdvanceSalaryRecordService() {
		return advanceSalaryRecordService;
	}

	/**
	 * Sets the advance salary record remote service.
	 *
	 * @param advanceSalaryRecordService the advance salary record remote service
	 */
	public void setAdvanceSalaryRecordService(
		com.vy.payroll.service.AdvanceSalaryRecordService advanceSalaryRecordService) {
		this.advanceSalaryRecordService = advanceSalaryRecordService;
	}

	/**
	 * Returns the advance salary record persistence.
	 *
	 * @return the advance salary record persistence
	 */
	public AdvanceSalaryRecordPersistence getAdvanceSalaryRecordPersistence() {
		return advanceSalaryRecordPersistence;
	}

	/**
	 * Sets the advance salary record persistence.
	 *
	 * @param advanceSalaryRecordPersistence the advance salary record persistence
	 */
	public void setAdvanceSalaryRecordPersistence(
		AdvanceSalaryRecordPersistence advanceSalaryRecordPersistence) {
		this.advanceSalaryRecordPersistence = advanceSalaryRecordPersistence;
	}

	/**
	 * Returns the advance salary record finder.
	 *
	 * @return the advance salary record finder
	 */
	public AdvanceSalaryRecordFinder getAdvanceSalaryRecordFinder() {
		return advanceSalaryRecordFinder;
	}

	/**
	 * Sets the advance salary record finder.
	 *
	 * @param advanceSalaryRecordFinder the advance salary record finder
	 */
	public void setAdvanceSalaryRecordFinder(
		AdvanceSalaryRecordFinder advanceSalaryRecordFinder) {
		this.advanceSalaryRecordFinder = advanceSalaryRecordFinder;
	}

	/**
	 * Returns the ctc detail local service.
	 *
	 * @return the ctc detail local service
	 */
	public com.vy.payroll.service.CtcDetailLocalService getCtcDetailLocalService() {
		return ctcDetailLocalService;
	}

	/**
	 * Sets the ctc detail local service.
	 *
	 * @param ctcDetailLocalService the ctc detail local service
	 */
	public void setCtcDetailLocalService(
		com.vy.payroll.service.CtcDetailLocalService ctcDetailLocalService) {
		this.ctcDetailLocalService = ctcDetailLocalService;
	}

	/**
	 * Returns the ctc detail remote service.
	 *
	 * @return the ctc detail remote service
	 */
	public com.vy.payroll.service.CtcDetailService getCtcDetailService() {
		return ctcDetailService;
	}

	/**
	 * Sets the ctc detail remote service.
	 *
	 * @param ctcDetailService the ctc detail remote service
	 */
	public void setCtcDetailService(
		com.vy.payroll.service.CtcDetailService ctcDetailService) {
		this.ctcDetailService = ctcDetailService;
	}

	/**
	 * Returns the ctc detail persistence.
	 *
	 * @return the ctc detail persistence
	 */
	public CtcDetailPersistence getCtcDetailPersistence() {
		return ctcDetailPersistence;
	}

	/**
	 * Sets the ctc detail persistence.
	 *
	 * @param ctcDetailPersistence the ctc detail persistence
	 */
	public void setCtcDetailPersistence(
		CtcDetailPersistence ctcDetailPersistence) {
		this.ctcDetailPersistence = ctcDetailPersistence;
	}

	/**
	 * Returns the department local service.
	 *
	 * @return the department local service
	 */
	public com.vy.payroll.service.DepartmentLocalService getDepartmentLocalService() {
		return departmentLocalService;
	}

	/**
	 * Sets the department local service.
	 *
	 * @param departmentLocalService the department local service
	 */
	public void setDepartmentLocalService(
		com.vy.payroll.service.DepartmentLocalService departmentLocalService) {
		this.departmentLocalService = departmentLocalService;
	}

	/**
	 * Returns the department remote service.
	 *
	 * @return the department remote service
	 */
	public com.vy.payroll.service.DepartmentService getDepartmentService() {
		return departmentService;
	}

	/**
	 * Sets the department remote service.
	 *
	 * @param departmentService the department remote service
	 */
	public void setDepartmentService(
		com.vy.payroll.service.DepartmentService departmentService) {
		this.departmentService = departmentService;
	}

	/**
	 * Returns the department persistence.
	 *
	 * @return the department persistence
	 */
	public DepartmentPersistence getDepartmentPersistence() {
		return departmentPersistence;
	}

	/**
	 * Sets the department persistence.
	 *
	 * @param departmentPersistence the department persistence
	 */
	public void setDepartmentPersistence(
		DepartmentPersistence departmentPersistence) {
		this.departmentPersistence = departmentPersistence;
	}

	/**
	 * Returns the document local service.
	 *
	 * @return the document local service
	 */
	public com.vy.payroll.service.DocumentLocalService getDocumentLocalService() {
		return documentLocalService;
	}

	/**
	 * Sets the document local service.
	 *
	 * @param documentLocalService the document local service
	 */
	public void setDocumentLocalService(
		com.vy.payroll.service.DocumentLocalService documentLocalService) {
		this.documentLocalService = documentLocalService;
	}

	/**
	 * Returns the document remote service.
	 *
	 * @return the document remote service
	 */
	public com.vy.payroll.service.DocumentService getDocumentService() {
		return documentService;
	}

	/**
	 * Sets the document remote service.
	 *
	 * @param documentService the document remote service
	 */
	public void setDocumentService(
		com.vy.payroll.service.DocumentService documentService) {
		this.documentService = documentService;
	}

	/**
	 * Returns the document persistence.
	 *
	 * @return the document persistence
	 */
	public DocumentPersistence getDocumentPersistence() {
		return documentPersistence;
	}

	/**
	 * Sets the document persistence.
	 *
	 * @param documentPersistence the document persistence
	 */
	public void setDocumentPersistence(DocumentPersistence documentPersistence) {
		this.documentPersistence = documentPersistence;
	}

	/**
	 * Returns the document finder.
	 *
	 * @return the document finder
	 */
	public DocumentFinder getDocumentFinder() {
		return documentFinder;
	}

	/**
	 * Sets the document finder.
	 *
	 * @param documentFinder the document finder
	 */
	public void setDocumentFinder(DocumentFinder documentFinder) {
		this.documentFinder = documentFinder;
	}

	/**
	 * Returns the employee details local service.
	 *
	 * @return the employee details local service
	 */
	public com.vy.payroll.service.EmployeeDetailsLocalService getEmployeeDetailsLocalService() {
		return employeeDetailsLocalService;
	}

	/**
	 * Sets the employee details local service.
	 *
	 * @param employeeDetailsLocalService the employee details local service
	 */
	public void setEmployeeDetailsLocalService(
		com.vy.payroll.service.EmployeeDetailsLocalService employeeDetailsLocalService) {
		this.employeeDetailsLocalService = employeeDetailsLocalService;
	}

	/**
	 * Returns the employee details remote service.
	 *
	 * @return the employee details remote service
	 */
	public com.vy.payroll.service.EmployeeDetailsService getEmployeeDetailsService() {
		return employeeDetailsService;
	}

	/**
	 * Sets the employee details remote service.
	 *
	 * @param employeeDetailsService the employee details remote service
	 */
	public void setEmployeeDetailsService(
		com.vy.payroll.service.EmployeeDetailsService employeeDetailsService) {
		this.employeeDetailsService = employeeDetailsService;
	}

	/**
	 * Returns the employee details persistence.
	 *
	 * @return the employee details persistence
	 */
	public EmployeeDetailsPersistence getEmployeeDetailsPersistence() {
		return employeeDetailsPersistence;
	}

	/**
	 * Sets the employee details persistence.
	 *
	 * @param employeeDetailsPersistence the employee details persistence
	 */
	public void setEmployeeDetailsPersistence(
		EmployeeDetailsPersistence employeeDetailsPersistence) {
		this.employeeDetailsPersistence = employeeDetailsPersistence;
	}

	/**
	 * Returns the leave request local service.
	 *
	 * @return the leave request local service
	 */
	public com.vy.payroll.service.LeaveRequestLocalService getLeaveRequestLocalService() {
		return leaveRequestLocalService;
	}

	/**
	 * Sets the leave request local service.
	 *
	 * @param leaveRequestLocalService the leave request local service
	 */
	public void setLeaveRequestLocalService(
		com.vy.payroll.service.LeaveRequestLocalService leaveRequestLocalService) {
		this.leaveRequestLocalService = leaveRequestLocalService;
	}

	/**
	 * Returns the leave request remote service.
	 *
	 * @return the leave request remote service
	 */
	public LeaveRequestService getLeaveRequestService() {
		return leaveRequestService;
	}

	/**
	 * Sets the leave request remote service.
	 *
	 * @param leaveRequestService the leave request remote service
	 */
	public void setLeaveRequestService(LeaveRequestService leaveRequestService) {
		this.leaveRequestService = leaveRequestService;
	}

	/**
	 * Returns the leave request persistence.
	 *
	 * @return the leave request persistence
	 */
	public LeaveRequestPersistence getLeaveRequestPersistence() {
		return leaveRequestPersistence;
	}

	/**
	 * Sets the leave request persistence.
	 *
	 * @param leaveRequestPersistence the leave request persistence
	 */
	public void setLeaveRequestPersistence(
		LeaveRequestPersistence leaveRequestPersistence) {
		this.leaveRequestPersistence = leaveRequestPersistence;
	}

	/**
	 * Returns the leave request finder.
	 *
	 * @return the leave request finder
	 */
	public LeaveRequestFinder getLeaveRequestFinder() {
		return leaveRequestFinder;
	}

	/**
	 * Sets the leave request finder.
	 *
	 * @param leaveRequestFinder the leave request finder
	 */
	public void setLeaveRequestFinder(LeaveRequestFinder leaveRequestFinder) {
		this.leaveRequestFinder = leaveRequestFinder;
	}

	/**
	 * Returns the payslip details local service.
	 *
	 * @return the payslip details local service
	 */
	public com.vy.payroll.service.PayslipDetailsLocalService getPayslipDetailsLocalService() {
		return payslipDetailsLocalService;
	}

	/**
	 * Sets the payslip details local service.
	 *
	 * @param payslipDetailsLocalService the payslip details local service
	 */
	public void setPayslipDetailsLocalService(
		com.vy.payroll.service.PayslipDetailsLocalService payslipDetailsLocalService) {
		this.payslipDetailsLocalService = payslipDetailsLocalService;
	}

	/**
	 * Returns the payslip details remote service.
	 *
	 * @return the payslip details remote service
	 */
	public com.vy.payroll.service.PayslipDetailsService getPayslipDetailsService() {
		return payslipDetailsService;
	}

	/**
	 * Sets the payslip details remote service.
	 *
	 * @param payslipDetailsService the payslip details remote service
	 */
	public void setPayslipDetailsService(
		com.vy.payroll.service.PayslipDetailsService payslipDetailsService) {
		this.payslipDetailsService = payslipDetailsService;
	}

	/**
	 * Returns the payslip details persistence.
	 *
	 * @return the payslip details persistence
	 */
	public PayslipDetailsPersistence getPayslipDetailsPersistence() {
		return payslipDetailsPersistence;
	}

	/**
	 * Sets the payslip details persistence.
	 *
	 * @param payslipDetailsPersistence the payslip details persistence
	 */
	public void setPayslipDetailsPersistence(
		PayslipDetailsPersistence payslipDetailsPersistence) {
		this.payslipDetailsPersistence = payslipDetailsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LeaveRequestService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LeaveRequest.class;
	}

	protected String getModelClassName() {
		return LeaveRequest.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = leaveRequestPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.vy.payroll.service.Admin_detailsLocalService.class)
	protected com.vy.payroll.service.Admin_detailsLocalService admin_detailsLocalService;
	@BeanReference(type = com.vy.payroll.service.Admin_detailsService.class)
	protected com.vy.payroll.service.Admin_detailsService admin_detailsService;
	@BeanReference(type = Admin_detailsPersistence.class)
	protected Admin_detailsPersistence admin_detailsPersistence;
	@BeanReference(type = com.vy.payroll.service.AdvanceSalaryRecordLocalService.class)
	protected com.vy.payroll.service.AdvanceSalaryRecordLocalService advanceSalaryRecordLocalService;
	@BeanReference(type = com.vy.payroll.service.AdvanceSalaryRecordService.class)
	protected com.vy.payroll.service.AdvanceSalaryRecordService advanceSalaryRecordService;
	@BeanReference(type = AdvanceSalaryRecordPersistence.class)
	protected AdvanceSalaryRecordPersistence advanceSalaryRecordPersistence;
	@BeanReference(type = AdvanceSalaryRecordFinder.class)
	protected AdvanceSalaryRecordFinder advanceSalaryRecordFinder;
	@BeanReference(type = com.vy.payroll.service.CtcDetailLocalService.class)
	protected com.vy.payroll.service.CtcDetailLocalService ctcDetailLocalService;
	@BeanReference(type = com.vy.payroll.service.CtcDetailService.class)
	protected com.vy.payroll.service.CtcDetailService ctcDetailService;
	@BeanReference(type = CtcDetailPersistence.class)
	protected CtcDetailPersistence ctcDetailPersistence;
	@BeanReference(type = com.vy.payroll.service.DepartmentLocalService.class)
	protected com.vy.payroll.service.DepartmentLocalService departmentLocalService;
	@BeanReference(type = com.vy.payroll.service.DepartmentService.class)
	protected com.vy.payroll.service.DepartmentService departmentService;
	@BeanReference(type = DepartmentPersistence.class)
	protected DepartmentPersistence departmentPersistence;
	@BeanReference(type = com.vy.payroll.service.DocumentLocalService.class)
	protected com.vy.payroll.service.DocumentLocalService documentLocalService;
	@BeanReference(type = com.vy.payroll.service.DocumentService.class)
	protected com.vy.payroll.service.DocumentService documentService;
	@BeanReference(type = DocumentPersistence.class)
	protected DocumentPersistence documentPersistence;
	@BeanReference(type = DocumentFinder.class)
	protected DocumentFinder documentFinder;
	@BeanReference(type = com.vy.payroll.service.EmployeeDetailsLocalService.class)
	protected com.vy.payroll.service.EmployeeDetailsLocalService employeeDetailsLocalService;
	@BeanReference(type = com.vy.payroll.service.EmployeeDetailsService.class)
	protected com.vy.payroll.service.EmployeeDetailsService employeeDetailsService;
	@BeanReference(type = EmployeeDetailsPersistence.class)
	protected EmployeeDetailsPersistence employeeDetailsPersistence;
	@BeanReference(type = com.vy.payroll.service.LeaveRequestLocalService.class)
	protected com.vy.payroll.service.LeaveRequestLocalService leaveRequestLocalService;
	@BeanReference(type = LeaveRequestService.class)
	protected LeaveRequestService leaveRequestService;
	@BeanReference(type = LeaveRequestPersistence.class)
	protected LeaveRequestPersistence leaveRequestPersistence;
	@BeanReference(type = LeaveRequestFinder.class)
	protected LeaveRequestFinder leaveRequestFinder;
	@BeanReference(type = com.vy.payroll.service.PayslipDetailsLocalService.class)
	protected com.vy.payroll.service.PayslipDetailsLocalService payslipDetailsLocalService;
	@BeanReference(type = com.vy.payroll.service.PayslipDetailsService.class)
	protected com.vy.payroll.service.PayslipDetailsService payslipDetailsService;
	@BeanReference(type = PayslipDetailsPersistence.class)
	protected PayslipDetailsPersistence payslipDetailsPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}