/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vy.payroll.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdvanceSalaryRecord service. Represents a row in the &quot;advance_salary_records&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vy.payroll.model.impl.AdvanceSalaryRecordModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vy.payroll.model.impl.AdvanceSalaryRecordImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AdvanceSalaryRecord
 * @see com.vy.payroll.model.impl.AdvanceSalaryRecordImpl
 * @see com.vy.payroll.model.impl.AdvanceSalaryRecordModelImpl
 * @generated
 */
@ProviderType
public interface AdvanceSalaryRecordModel extends BaseModel<AdvanceSalaryRecord> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a advance salary record model instance should use the {@link AdvanceSalaryRecord} interface instead.
	 */

	/**
	 * Returns the primary key of this advance salary record.
	 *
	 * @return the primary key of this advance salary record
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this advance salary record.
	 *
	 * @param primaryKey the primary key of this advance salary record
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the request_id of this advance salary record.
	 *
	 * @return the request_id of this advance salary record
	 */
	public int getRequest_id();

	/**
	 * Sets the request_id of this advance salary record.
	 *
	 * @param request_id the request_id of this advance salary record
	 */
	public void setRequest_id(int request_id);

	/**
	 * Returns the eid of this advance salary record.
	 *
	 * @return the eid of this advance salary record
	 */
	@AutoEscape
	public String getEid();

	/**
	 * Sets the eid of this advance salary record.
	 *
	 * @param eid the eid of this advance salary record
	 */
	public void setEid(String eid);

	/**
	 * Returns the reason of this advance salary record.
	 *
	 * @return the reason of this advance salary record
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this advance salary record.
	 *
	 * @param reason the reason of this advance salary record
	 */
	public void setReason(String reason);

	/**
	 * Returns the is_checked of this advance salary record.
	 *
	 * @return the is_checked of this advance salary record
	 */
	@AutoEscape
	public String getIs_checked();

	/**
	 * Sets the is_checked of this advance salary record.
	 *
	 * @param is_checked the is_checked of this advance salary record
	 */
	public void setIs_checked(String is_checked);

	/**
	 * Returns the date of this advance salary record.
	 *
	 * @return the date of this advance salary record
	 */
	public Date getDate();

	/**
	 * Sets the date of this advance salary record.
	 *
	 * @param date the date of this advance salary record
	 */
	public void setDate(Date date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AdvanceSalaryRecord advanceSalaryRecord);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AdvanceSalaryRecord> toCacheModel();

	@Override
	public AdvanceSalaryRecord toEscapedModel();

	@Override
	public AdvanceSalaryRecord toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}