/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vy.payroll.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CtcDetail service. Represents a row in the &quot;ctc_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vy.payroll.model.impl.CtcDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vy.payroll.model.impl.CtcDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CtcDetail
 * @see com.vy.payroll.model.impl.CtcDetailImpl
 * @see com.vy.payroll.model.impl.CtcDetailModelImpl
 * @generated
 */
@ProviderType
public interface CtcDetailModel extends BaseModel<CtcDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ctc detail model instance should use the {@link CtcDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this ctc detail.
	 *
	 * @return the primary key of this ctc detail
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ctc detail.
	 *
	 * @param primaryKey the primary key of this ctc detail
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ctc of this ctc detail.
	 *
	 * @return the ctc of this ctc detail
	 */
	public int getCtc();

	/**
	 * Sets the ctc of this ctc detail.
	 *
	 * @param ctc the ctc of this ctc detail
	 */
	public void setCtc(int ctc);

	/**
	 * Returns the hra of this ctc detail.
	 *
	 * @return the hra of this ctc detail
	 */
	public int getHra();

	/**
	 * Sets the hra of this ctc detail.
	 *
	 * @param hra the hra of this ctc detail
	 */
	public void setHra(int hra);

	/**
	 * Returns the ma of this ctc detail.
	 *
	 * @return the ma of this ctc detail
	 */
	public int getMa();

	/**
	 * Sets the ma of this ctc detail.
	 *
	 * @param ma the ma of this ctc detail
	 */
	public void setMa(int ma);

	/**
	 * Returns the ca of this ctc detail.
	 *
	 * @return the ca of this ctc detail
	 */
	public int getCa();

	/**
	 * Sets the ca of this ctc detail.
	 *
	 * @param ca the ca of this ctc detail
	 */
	public void setCa(int ca);

	/**
	 * Returns the ta of this ctc detail.
	 *
	 * @return the ta of this ctc detail
	 */
	public int getTa();

	/**
	 * Sets the ta of this ctc detail.
	 *
	 * @param ta the ta of this ctc detail
	 */
	public void setTa(int ta);

	/**
	 * Returns the pf of this ctc detail.
	 *
	 * @return the pf of this ctc detail
	 */
	public int getPf();

	/**
	 * Sets the pf of this ctc detail.
	 *
	 * @param pf the pf of this ctc detail
	 */
	public void setPf(int pf);

	/**
	 * Returns the sa of this ctc detail.
	 *
	 * @return the sa of this ctc detail
	 */
	public int getSa();

	/**
	 * Sets the sa of this ctc detail.
	 *
	 * @param sa the sa of this ctc detail
	 */
	public void setSa(int sa);

	/**
	 * Returns the income tax of this ctc detail.
	 *
	 * @return the income tax of this ctc detail
	 */
	public int getIncomeTax();

	/**
	 * Sets the income tax of this ctc detail.
	 *
	 * @param incomeTax the income tax of this ctc detail
	 */
	public void setIncomeTax(int incomeTax);

	/**
	 * Returns the proffesional tax of this ctc detail.
	 *
	 * @return the proffesional tax of this ctc detail
	 */
	public int getProffesionalTax();

	/**
	 * Sets the proffesional tax of this ctc detail.
	 *
	 * @param proffesionalTax the proffesional tax of this ctc detail
	 */
	public void setProffesionalTax(int proffesionalTax);

	/**
	 * Returns the basic salary of this ctc detail.
	 *
	 * @return the basic salary of this ctc detail
	 */
	public int getBasicSalary();

	/**
	 * Sets the basic salary of this ctc detail.
	 *
	 * @param basicSalary the basic salary of this ctc detail
	 */
	public void setBasicSalary(int basicSalary);

	/**
	 * Returns the contribution amt of this ctc detail.
	 *
	 * @return the contribution amt of this ctc detail
	 */
	public int getContributionAmt();

	/**
	 * Sets the contribution amt of this ctc detail.
	 *
	 * @param contributionAmt the contribution amt of this ctc detail
	 */
	public void setContributionAmt(int contributionAmt);

	/**
	 * Returns the gratuity of this ctc detail.
	 *
	 * @return the gratuity of this ctc detail
	 */
	public int getGratuity();

	/**
	 * Sets the gratuity of this ctc detail.
	 *
	 * @param gratuity the gratuity of this ctc detail
	 */
	public void setGratuity(int gratuity);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CtcDetail ctcDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CtcDetail> toCacheModel();

	@Override
	public CtcDetail toEscapedModel();

	@Override
	public CtcDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}