/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vy.payroll.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the PayslipDetails service. Represents a row in the &quot;payslip_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vy.payroll.model.impl.PayslipDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vy.payroll.model.impl.PayslipDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PayslipDetails
 * @see com.vy.payroll.model.impl.PayslipDetailsImpl
 * @see com.vy.payroll.model.impl.PayslipDetailsModelImpl
 * @generated
 */
@ProviderType
public interface PayslipDetailsModel extends BaseModel<PayslipDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payslip details model instance should use the {@link PayslipDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this payslip details.
	 *
	 * @return the primary key of this payslip details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this payslip details.
	 *
	 * @param primaryKey the primary key of this payslip details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ctc ID of this payslip details.
	 *
	 * @return the ctc ID of this payslip details
	 */
	public long getCtcId();

	/**
	 * Sets the ctc ID of this payslip details.
	 *
	 * @param ctcId the ctc ID of this payslip details
	 */
	public void setCtcId(long ctcId);

	/**
	 * Returns the ctc of this payslip details.
	 *
	 * @return the ctc of this payslip details
	 */
	public int getCtc();

	/**
	 * Sets the ctc of this payslip details.
	 *
	 * @param ctc the ctc of this payslip details
	 */
	public void setCtc(int ctc);

	/**
	 * Returns the hra of this payslip details.
	 *
	 * @return the hra of this payslip details
	 */
	public int getHra();

	/**
	 * Sets the hra of this payslip details.
	 *
	 * @param hra the hra of this payslip details
	 */
	public void setHra(int hra);

	/**
	 * Returns the ma of this payslip details.
	 *
	 * @return the ma of this payslip details
	 */
	public int getMa();

	/**
	 * Sets the ma of this payslip details.
	 *
	 * @param ma the ma of this payslip details
	 */
	public void setMa(int ma);

	/**
	 * Returns the ca of this payslip details.
	 *
	 * @return the ca of this payslip details
	 */
	public int getCa();

	/**
	 * Sets the ca of this payslip details.
	 *
	 * @param ca the ca of this payslip details
	 */
	public void setCa(int ca);

	/**
	 * Returns the ta of this payslip details.
	 *
	 * @return the ta of this payslip details
	 */
	public int getTa();

	/**
	 * Sets the ta of this payslip details.
	 *
	 * @param ta the ta of this payslip details
	 */
	public void setTa(int ta);

	/**
	 * Returns the pf of this payslip details.
	 *
	 * @return the pf of this payslip details
	 */
	public int getPf();

	/**
	 * Sets the pf of this payslip details.
	 *
	 * @param pf the pf of this payslip details
	 */
	public void setPf(int pf);

	/**
	 * Returns the sa of this payslip details.
	 *
	 * @return the sa of this payslip details
	 */
	public int getSa();

	/**
	 * Sets the sa of this payslip details.
	 *
	 * @param sa the sa of this payslip details
	 */
	public void setSa(int sa);

	/**
	 * Returns the income tax of this payslip details.
	 *
	 * @return the income tax of this payslip details
	 */
	public int getIncomeTax();

	/**
	 * Sets the income tax of this payslip details.
	 *
	 * @param incomeTax the income tax of this payslip details
	 */
	public void setIncomeTax(int incomeTax);

	/**
	 * Returns the net salary of this payslip details.
	 *
	 * @return the net salary of this payslip details
	 */
	public int getNetSalary();

	/**
	 * Sets the net salary of this payslip details.
	 *
	 * @param netSalary the net salary of this payslip details
	 */
	public void setNetSalary(int netSalary);

	/**
	 * Returns the month of this payslip details.
	 *
	 * @return the month of this payslip details
	 */
	public int getMonth();

	/**
	 * Sets the month of this payslip details.
	 *
	 * @param month the month of this payslip details
	 */
	public void setMonth(int month);

	/**
	 * Returns the eid of this payslip details.
	 *
	 * @return the eid of this payslip details
	 */
	@AutoEscape
	public String getEid();

	/**
	 * Sets the eid of this payslip details.
	 *
	 * @param eid the eid of this payslip details
	 */
	public void setEid(String eid);

	/**
	 * Returns the basic salary of this payslip details.
	 *
	 * @return the basic salary of this payslip details
	 */
	public int getBasicSalary();

	/**
	 * Sets the basic salary of this payslip details.
	 *
	 * @param basicSalary the basic salary of this payslip details
	 */
	public void setBasicSalary(int basicSalary);

	/**
	 * Returns the proffesional tax of this payslip details.
	 *
	 * @return the proffesional tax of this payslip details
	 */
	public int getProffesionalTax();

	/**
	 * Sets the proffesional tax of this payslip details.
	 *
	 * @param proffesionalTax the proffesional tax of this payslip details
	 */
	public void setProffesionalTax(int proffesionalTax);

	/**
	 * Returns the taxabl amt of this payslip details.
	 *
	 * @return the taxabl amt of this payslip details
	 */
	public int getTaxablAmt();

	/**
	 * Sets the taxabl amt of this payslip details.
	 *
	 * @param TaxablAmt the taxabl amt of this payslip details
	 */
	public void setTaxablAmt(int TaxablAmt);

	/**
	 * Returns the gratuity of this payslip details.
	 *
	 * @return the gratuity of this payslip details
	 */
	public int getGratuity();

	/**
	 * Sets the gratuity of this payslip details.
	 *
	 * @param gratuity the gratuity of this payslip details
	 */
	public void setGratuity(int gratuity);

	/**
	 * Returns the gross salary of this payslip details.
	 *
	 * @return the gross salary of this payslip details
	 */
	public int getGrossSalary();

	/**
	 * Sets the gross salary of this payslip details.
	 *
	 * @param grossSalary the gross salary of this payslip details
	 */
	public void setGrossSalary(int grossSalary);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PayslipDetails payslipDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PayslipDetails> toCacheModel();

	@Override
	public PayslipDetails toEscapedModel();

	@Override
	public PayslipDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}